/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxyscan;

import java.util.ArrayList;
import java.util.Vector;
import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author sushil
 */
public class ProxyScan extends javax.swing.JFrame {

    static BlockingQueue<String> validProxy;
    static int threadNumber = 0;
    public static Vector listData = new Vector();
    ArrayList<String> proxyList = new ArrayList();
    public ProxyScan() {
        this.validProxy = new ArrayBlockingQueue(50);
        initComponents();
        Loader.setVisible(false);
        scanAgain.setVisible(false);
        String Base = "172.30.0.";
        for(int i = 1;i<100;i++){
            String S = Base + i;
            proxyList.add(S);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        scanBtn = new javax.swing.JButton();
        Loader = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        myList = new javax.swing.JList();
        scanAgain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        urlBar.setText("type the url over here");

        jLabel1.setText("https://");

        scanBtn.setText("Scan");
        scanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanBtnMouseClicked(evt);
            }
        });

        Loader.setText("Loading...");

        myList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(myList);

        scanAgain.setText("Scan Again?");
        scanAgain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scanAgainMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Loader)
                        .addGap(46, 46, 46)
                        .addComponent(scanAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scanBtn))
                    .addComponent(urlBar, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scanBtn)
                    .addComponent(Loader)
                    .addComponent(scanAgain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanBtnMouseClicked
        listData.clear();
        scanBtn.hide();
        Loader.show();
        String url = "https://" + urlBar.getText();
        SwingUtilities.invokeLater(new Runnable(){

            @Override
            public void run() {
                findMain();
            }
            
        });
   
    }//GEN-LAST:event_scanBtnMouseClicked
    
    public void findMain(){
        String url = urlBar.getText();
        if(url.contains("www."))
            url = url.substring(4, url.length());
        url = "https://" + urlBar.getText();
        ArrayList<Thread>ThreadList = new ArrayList();
        for(int i = 0;i<proxyList.size();i++){
            ThreadList.add(new Thread(new ScannerThread(proxyList.get(i),url)));
            ThreadList.get(i).start();
        }
        
        for(int i = 0;i<ThreadList.size();i++){
            try {
                ThreadList.get(i).join();
            } catch (InterruptedException ex) {
                Logger.getLogger(ProxyScan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        Loader.setVisible(false);
        scanAgain.setVisible(true);
        ThreadList.clear();
    }
    
    private void scanAgainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scanAgainMouseClicked
        scanBtn.setVisible(true);
        scanAgain.setVisible(false);
        urlBar.setText(" ");
    }//GEN-LAST:event_scanAgainMouseClicked

    public static void updateThread(){
        threadNumber += 1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProxyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProxyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProxyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProxyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProxyScan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Loader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JList myList;
    private javax.swing.JButton scanAgain;
    private javax.swing.JButton scanBtn;
    private javax.swing.JTextField urlBar;
    // End of variables declaration//GEN-END:variables
}
